version: '3'

services:

  server:
    image: node/server
    build: .
    ports:
      - "3333:3333"
    command: npm start
    environment:
      PORT: 3333
    volumes:
      - .:/usr/server  

  mongo_database:
    image: 'mongo'
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/data/db